#!/bin/sh
#script for save and restore file timestamp

TIMEFILE="/tmp/pushftime"
if [ ! -f $1 ]
then
    echo "[Error] $1 is not a file."
    exit
fi

if [ ${0##*/} = "pushftime" ]
then
    MTIME=`stat -c %y $1`
    echo $MTIME > $TIMEFILE
    echo "[Info] Time \"$MTIME\" save to $TIMEFILE"
else
    MTIME=`cat $TIMEFILE`
    touch -d "$MTIME" $1
    rm $TIMEFILE
    echo "[Info] Time \"$MTIME\" write to $1"
fi
